
all:
	cd libft && make
	cd printf && make
	cd framework && make

clean:
	cd libft && make clean
	cd printf && make clean
	cd framework && make clean

fclean:
	cd libft && make fclean
	cd printf && make fclean
	cd framework && make fclean

re: fclean
	cd libft && make re
	cd printf && make re
	cd framework && make re

.PHONY: all clean fclean re